/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.gltf
Author: Lunachan (https://sketchfab.com/Lunachan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roboter-cute-f52981724a4443c79396b77a415b3d7e
Title: Roboter_cute
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';


export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  const modelRef = useRef();
  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    modelRef.current.rotation.y = elapsedTime * 0.8; // Adjust the rotation speed as desired
  });
  return (
    <group {...props} dispose={null}  ref={modelRef}>
      <group scale={0.014}>
        <group position={[87.463, 109.807, 0]} scale={0.643}>
          <mesh geometry={nodes['Arm_wei��_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Arm_black_0.geometry} material={materials.black} />
        </group>
        <group scale={0.643}>
          <mesh geometry={nodes['K��rper_wei��_0'].geometry} material={materials.material} />
          <mesh geometry={nodes['K��rper_black_0'].geometry} material={materials.black} />
          <mesh geometry={nodes['K��rper_glass_0'].geometry} material={materials.glass} />
        </group>
        <group position={[0, 188.873, 0]} scale={[0.943, 0.821, 0.816]}>
          <mesh geometry={nodes['Kopf_wei��_0'].geometry} material={materials.material} />
          <mesh geometry={nodes.Kopf_blackscreen_0.geometry} material={materials.blackscreen} />
        </group>
        <group position={[69.066, 187.475, -0.034]} rotation={[0, 0, -Math.PI / 2]} scale={0.243}>
          <mesh geometry={nodes.Ohren_lilac_0.geometry} material={materials.lilac} />
          <mesh geometry={nodes.Ohren_grey_0.geometry} material={materials.grey} />
        </group>
        <mesh geometry={nodes.Mond_Bauch_light_Yellow_0.geometry} material={materials.light_Yellow} position={[5.149, 64.768, 36.026]} rotation={[-0.647, 1.515, -1.284]} scale={0.119} />
        <mesh geometry={nodes.Strar_light_Yellow_0.geometry} material={materials.light_Yellow} position={[1.006, 267.788, -53.546]} rotation={[0.083, 0, 0]} scale={0.151} />
        <mesh geometry={nodes.Atenne_grey_0.geometry} material={materials.grey} position={[0.71, 264.936, -21.959]} scale={[0.052, 0.229, 0.048]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
